/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ProxyPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  enabled: false,
  proxyType: "http",
  host: "",
  port: "",
  username: "",
  password: ""
};
var ProxyPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new ProxySettingTab(this.app, this));
    if (this.settings.enabled) {
      await this.applyProxy();
    }
  }
  async onunload() {
    await this.clearProxy();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Builds a proxyRules string in Chromium's recognized format.
   *
   * Chromium documentation:
   *   https://www.chromium.org/developers/design-documents/network-settings/#proxy-configuration
   *
   * Format:
   *   [scheme://[user:pass@]]host:port
   *
   * Schemes:
   *   http   → HTTP/HTTPS proxy (Chromium routes both protocols)
   *   socks5 → SOCKS5 proxy (DNS resolution happens on the proxy side)
   */
  buildProxyRules() {
    const { proxyType, host, port, username, password } = this.settings;
    if (!host || !port)
      return "";
    const auth = username && password ? `${encodeURIComponent(username)}:${encodeURIComponent(password)}@` : "";
    if (proxyType === "socks5") {
      return `socks5://${auth}${host}:${port}`;
    }
    return `http=${auth}${host}:${port};https=${auth}${host}:${port}`;
  }
  /**
   * Applies proxy configuration to the default Electron session.
   *
   * Key call: session.defaultSession.setProxy()
   *   - config argument: { proxyRules, proxyBypassRules }
   *   - proxyRules: routing string (see buildProxyRules)
   *   - proxyBypassRules: domains that bypass the proxy
   *     (empty = all traffic goes through proxy)
   *
   * After setProxy, Chromium updates the route for new TCP connections.
   */
  async applyProxy() {
    var _a, _b, _c, _d, _e;
    const rules = this.buildProxyRules();
    if (!rules) {
      new import_obsidian.Notice("Global Proxy: host and port are required");
      return false;
    }
    try {
      const electron = window.require("electron");
      const session = (_d = (_b = (_a = electron.remote) == null ? void 0 : _a.session) == null ? void 0 : _b.defaultSession) != null ? _d : (_c = electron.session) == null ? void 0 : _c.defaultSession;
      if (!session) {
        new import_obsidian.Notice("Global Proxy: cannot access Electron session");
        return false;
      }
      await session.setProxy({
        proxyRules: rules,
        proxyBypassRules: ""
      });
      new import_obsidian.Notice(
        `Global Proxy: ON (${this.settings.proxyType}://${this.settings.host}:${this.settings.port})`
      );
      return true;
    } catch (err) {
      console.error("Global Proxy apply error:", err);
      new import_obsidian.Notice(
        `Global Proxy: error applying proxy \u2014 ${(_e = err.message) != null ? _e : err}`
      );
      return false;
    }
  }
  /**
   * Clears proxy configuration — all traffic returns to direct.
   *
   * Calling setProxy({ proxyRules: "" }) clears routing rules,
   * and Chromium reverts to direct connections (DIRECT).
   */
  async clearProxy() {
    var _a, _b, _c, _d;
    try {
      const electron = window.require("electron");
      const session = (_d = (_b = (_a = electron.remote) == null ? void 0 : _a.session) == null ? void 0 : _b.defaultSession) != null ? _d : (_c = electron.session) == null ? void 0 : _c.defaultSession;
      if (session) {
        await session.setProxy({ proxyRules: "", proxyBypassRules: "" });
      }
    } catch (err) {
      console.error("Global Proxy clear error:", err);
    }
  }
  /**
   * Enable proxy: apply rules + persist enabled flag.
   */
  async enableProxy() {
    const ok = await this.applyProxy();
    this.settings.enabled = ok;
    await this.saveSettings();
  }
  /**
   * Disable proxy: clear rules + persist enabled=false.
   * User can toggle proxy off on the fly with a single click.
   */
  async disableProxy() {
    await this.clearProxy();
    this.settings.enabled = false;
    await this.saveSettings();
    new import_obsidian.Notice("Global Proxy: OFF \u2014 direct connection restored");
  }
  /**
   * Connection check via the current proxy.
   *
   * Makes a GET request to https://api.ipify.org?format=json
   * through Obsidian's requestUrl() — which internally uses fetch,
   * which in Electron goes through session proxy rules.
   *
   * If proxy is applied, the request goes through the proxy,
   * and ipify returns the proxy's IP instead of the user's real IP.
   */
  async checkConnection() {
    try {
      const resp = await (0, import_obsidian.requestUrl)({
        url: "https://api.ipify.org?format=json",
        method: "GET"
      });
      return resp.json;
    } catch (err) {
      console.error("Global Proxy check error:", err);
      return null;
    }
  }
};
var ProxyCheckModal = class extends import_obsidian.Modal {
  constructor(app, result, error, isProxyOn) {
    super(app);
    this.result = result;
    this.error = error;
    this.isProxyOn = isProxyOn;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("global-proxy-check-modal");
    contentEl.createEl("h2", { text: "Proxy Connection Check" });
    if (!this.isProxyOn) {
      contentEl.createEl("p", {
        text: "Proxy is currently OFF. The IP below is your real IP (direct connection).",
        cls: "global-proxy-check-result"
      });
    }
    if (this.error) {
      contentEl.createEl("p", {
        text: `Error: ${this.error}`,
        cls: "global-proxy-check-result",
        attr: {
          style: "background: var(--background-modifier-error); color: var(--text-error);"
        }
      });
      contentEl.createEl("p", {
        text: "The proxy server is unreachable or the credentials are incorrect. Click the toggle to disable the proxy and restore direct connection."
      });
    } else if (this.result) {
      contentEl.createEl("p", {
        text: `Current outgoing IP: ${this.result.ip}`,
        cls: "global-proxy-check-result",
        attr: {
          style: "background: var(--background-modifier-success); color: var(--text-success);"
        }
      });
      if (this.isProxyOn) {
        contentEl.createEl("p", {
          text: "This IP belongs to your proxy server. Connection is working correctly."
        });
      }
    }
    new import_obsidian.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Close").onClick(() => this.close())
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ProxySettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.statusEl = null;
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("global-proxy-settings");
    containerEl.createEl("h2", { text: "Global Proxy Settings" });
    this.statusEl = containerEl.createEl("div", {
      cls: `global-proxy-status ${this.plugin.settings.enabled ? "active" : "inactive"}`,
      text: this.plugin.settings.enabled ? `Proxy ON \u2014 ${this.plugin.settings.proxyType}://${this.plugin.settings.host}:${this.plugin.settings.port}` : "Proxy OFF \u2014 direct connection"
    });
    new import_obsidian.Setting(containerEl).setName("Enable proxy").setDesc("Toggle proxy on/off without restarting Obsidian").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enabled).onChange(async (val) => {
        if (val) {
          await this.plugin.enableProxy();
        } else {
          await this.plugin.disableProxy();
        }
        this.refreshStatus();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Proxy type").setDesc(
      "HTTP proxy handles HTTP/HTTPS traffic. SOCKS5 proxies all TCP with DNS resolution on the proxy side."
    ).addDropdown(
      (dd) => dd.addOption("http", "HTTP").addOption("socks5", "SOCKS5").setValue(this.plugin.settings.proxyType).onChange(async (val) => {
        this.plugin.settings.proxyType = val;
        await this.plugin.saveSettings();
        if (this.plugin.settings.enabled) {
          await this.plugin.enableProxy();
          this.refreshStatus();
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("Host").setDesc("IP address or hostname of the proxy server").addText(
      (text) => text.setPlaceholder("e.g. 127.0.0.1").setValue(this.plugin.settings.host).onChange(async (val) => {
        this.plugin.settings.host = val.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Port").setDesc("Port number of the proxy server").addText(
      (text) => text.setPlaceholder("e.g. 8080").setValue(this.plugin.settings.port).onChange(async (val) => {
        this.plugin.settings.port = val.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Username").setDesc("Leave empty if proxy does not require authentication").addText(
      (text) => text.setPlaceholder("optional").setValue(this.plugin.settings.username).onChange(async (val) => {
        this.plugin.settings.username = val;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Password").setDesc("Leave empty if proxy does not require authentication").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("optional").setValue(this.plugin.settings.password).onChange(async (val) => {
        this.plugin.settings.password = val;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Check Connection").setDesc(
      "Requests https://api.ipify.org through the current proxy to verify connectivity"
    ).addButton(
      (btn) => btn.setButtonText("Check Connection").onClick(async () => {
        btn.setButtonText("Checking...");
        btn.setDisabled(true);
        const result = await this.plugin.checkConnection();
        const error = result === null ? "Connection failed \u2014 proxy may be unreachable" : null;
        btn.setButtonText("Check Connection");
        btn.setDisabled(false);
        if (error) {
          new import_obsidian.Notice("Global Proxy: connection check failed", 5e3);
        } else if (result) {
          new import_obsidian.Notice(
            `Global Proxy: outgoing IP is ${result.ip}`,
            5e3
          );
        }
        const modal = new ProxyCheckModal(
          this.app,
          result,
          error,
          this.plugin.settings.enabled
        );
        modal.open();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Emergency Disable").setDesc(
      "Instantly clear proxy rules and restore direct connection"
    ).addButton(
      (btn) => btn.setButtonText("Disable Proxy Now").onClick(async () => {
        await this.plugin.disableProxy();
        this.refreshStatus();
      })
    );
  }
  refreshStatus() {
    if (!this.statusEl)
      return;
    this.statusEl.className = `global-proxy-status ${this.plugin.settings.enabled ? "active" : "inactive"}`;
    this.statusEl.textContent = this.plugin.settings.enabled ? `Proxy ON \u2014 ${this.plugin.settings.proxyType}://${this.plugin.settings.host}:${this.plugin.settings.port}` : "Proxy OFF \u2014 direct connection";
  }
};
