/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ObsiProxyPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  enabled: false,
  activeProxyId: "",
  proxies: []
};
function generateId() {
  return Date.now().toString(36) + Math.random().toString(36).slice(2, 8);
}
var ObsiProxyPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.sessionWatchInterval = null;
    this.originalEnv = /* @__PURE__ */ new Map();
    this.lastSessionCount = 0;
    this.loginHandler = null;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new ObsiProxySettingTab(this.app, this));
    if (this.settings.enabled && this.getActiveProxy()) {
      await this.applyProxy();
      this.startSessionWatch();
    }
  }
  async onunload() {
    this.stopSessionWatch();
    await this.clearProxy();
  }
  async loadSettings() {
    const loaded = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, loaded);
    if (!this.settings.proxies)
      this.settings.proxies = [];
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  getActiveProxy() {
    var _a;
    if (!this.settings.activeProxyId)
      return null;
    return (_a = this.settings.proxies.find(
      (p) => p.id === this.settings.activeProxyId
    )) != null ? _a : null;
  }
  // ──────────────────────────────────────────────────────────
  //  SESSION DISCOVERY
  // ──────────────────────────────────────────────────────────
  getRemote() {
    try {
      const electron = window.require("electron");
      if (electron.remote)
        return electron.remote;
    } catch (e) {
    }
    try {
      const remote = window.require("@electron/remote");
      if (remote)
        return remote;
    } catch (e) {
    }
    return null;
  }
  /**
   * Discover ALL Electron sessions.
   *
   * Critical: Obsidian uses separate sessions for Sync, plugin
   * downloads, webviews, etc. Applying proxy only to defaultSession
   * is NOT enough — other sessions bypass the proxy entirely.
   */
  async getAllSessions() {
    var _a, _b, _c, _d, _e, _f;
    const sessions = [];
    const seen = /* @__PURE__ */ new Set();
    const add = (s) => {
      if (s && typeof s.setProxy === "function" && !seen.has(s)) {
        seen.add(s);
        sessions.push(s);
      }
    };
    try {
      const electron = window.require("electron");
      const remote = this.getRemote();
      if (remote) {
        try {
          add((_a = remote.session) == null ? void 0 : _a.defaultSession);
        } catch (e) {
        }
        try {
          const win = remote.getCurrentWindow();
          add((_b = win == null ? void 0 : win.webContents) == null ? void 0 : _b.session);
        } catch (e) {
        }
        try {
          const windows = remote.BrowserWindow.getAllWindows();
          for (const win of windows) {
            try {
              add((_c = win.webContents) == null ? void 0 : _c.session);
            } catch (e) {
            }
          }
        } catch (e) {
        }
        const partitions = [
          "persist:obsidian",
          "persist:sync",
          "persist:plugins",
          "persist:themes",
          "persist:core",
          "persist:0",
          "persist:1",
          "persist:"
        ];
        for (const partition of partitions) {
          try {
            add((_e = (_d = remote.session) == null ? void 0 : _d.fromPartition) == null ? void 0 : _e.call(_d, partition));
          } catch (e) {
          }
        }
      }
      try {
        add((_f = electron.session) == null ? void 0 : _f.defaultSession);
      } catch (e) {
      }
    } catch (e) {
    }
    this.lastSessionCount = sessions.length;
    return sessions;
  }
  // ──────────────────────────────────────────────────────────
  //  PROXY RULES BUILDER
  // ──────────────────────────────────────────────────────────
  /**
   * Build Chromium-compatible proxyRules string.
   *
   * ─── CRITICAL FORMAT NOTE ───
   *
   * When credentials are present, the proxy URL MUST include the
   * scheme prefix (http://) explicitly. Without it, Chromium's
   * parser misinterprets the string:
   *
   *   WRONG: "http=user:pass@host:port"
   *     → Chromium sees "http=" as traffic type, then tries to
   *       parse "user:pass@host:port" as host:port
   *     → Result: host="user", port="pass@host..." → GARBAGE
   *
   *   CORRECT: "http=http://user:pass@host:port"
   *     → Chromium sees "http=" as traffic type, then parses
   *       "http://user:pass@host:port" as a URL with scheme
   *     → Result: correct extraction of user, pass, host, port
   *
   * Chromium proxy config format:
   *   proxy-rule = [ traffic-type "=" ] [ scheme "://" ] [ user ":" pass "@" ] host [ ":" port ]
   *   traffic-type = "http" | "https" | "ftp"
   *   scheme = "http" | "https" | "socks4" | "socks5" | "direct"
   *
   * Example for HTTP proxy with auth:
   *   "http=http://user:pass@host:port;https=http://user:pass@host:port"
   *
   * Example for SOCKS5 proxy with auth:
   *   "socks5://user:pass@host:port"
   */
  buildProxyRules(proxy) {
    const { proxyType, host, port, username, password } = proxy;
    if (!host || !port)
      return "";
    const auth = username && password ? `${encodeURIComponent(username)}:${encodeURIComponent(password)}@` : "";
    if (proxyType === "socks5") {
      return `socks5://${auth}${host}:${port}`;
    }
    if (username && password) {
      return `http=http://${auth}${host}:${port};https=http://${auth}${host}:${port}`;
    }
    return `http=${host}:${port};https=${host}:${port}`;
  }
  // ──────────────────────────────────────────────────────────
  //  LOGIN HANDLER (PROXY AUTH)
  // ──────────────────────────────────────────────────────────
  /**
   * Create a login handler for session.on('login').
   *
   * When a proxy sends 407 Proxy Authentication Required,
   * Chromium fires the 'login' event. Without a handler:
   *   - Chromium shows an invisible auth dialog in Electron
   *   - The request silently fails
   *   - The user sees "connection error" with no explanation
   *
   * With this handler:
   *   - We detect authInfo.isProxy (proxy auth challenge)
   *   - We provide the username/password via callback()
   *   - The proxy connection succeeds
   *
   * This is ESSENTIAL for proxies that require authentication.
   * Even if credentials are in proxyRules, Chromium may still
   * fire the 'login' event in some cases.
   */
  createLoginHandler(proxy) {
    return (event, _webContents, _request, authInfo, callback) => {
      if ((authInfo == null ? void 0 : authInfo.isProxy) && proxy.username && proxy.password) {
        event.preventDefault();
        callback(proxy.username, proxy.password);
      }
    };
  }
  /**
   * Register login handler on all discovered sessions.
   * Remove old handler first to prevent duplicates.
   */
  async registerLoginHandlers(proxy) {
    await this.unregisterLoginHandlers();
    this.loginHandler = this.createLoginHandler(proxy);
    const sessions = await this.getAllSessions();
    for (const session of sessions) {
      try {
        session.on("login", this.loginHandler);
      } catch (e) {
      }
    }
  }
  /**
   * Remove login handler from all sessions.
   */
  async unregisterLoginHandlers() {
    if (!this.loginHandler)
      return;
    const sessions = await this.getAllSessions();
    for (const session of sessions) {
      try {
        session.removeListener("login", this.loginHandler);
      } catch (e) {
      }
    }
    this.loginHandler = null;
  }
  // ──────────────────────────────────────────────────────────
  //  ENVIRONMENT VARIABLES
  // ──────────────────────────────────────────────────────────
  /**
   * Set process.env proxy variables.
   *
   * For HTTP proxy:
   *   HTTP_PROXY=http://user:pass@host:port
   *   HTTPS_PROXY=http://user:pass@host:port
   *   ALL_PROXY=http://user:pass@host:port
   *
   * For SOCKS5 proxy:
   *   HTTP_PROXY=socks5://user:pass@host:port  (for libs that support it)
   *   HTTPS_PROXY=socks5://user:pass@host:port
   *   ALL_PROXY=socks5://user:pass@host:port
   *
   * Note: Most HTTP libraries (axios, node-fetch) only understand
   * http:// scheme in HTTP_PROXY. For SOCKS5, they need
   * socks-proxy-agent or similar. ALL_PROXY with socks5:// is
   * the standard fallback for SOCKS5-aware libraries (got, etc.)
   */
  setEnvironmentProxy(proxy) {
    const auth = proxy.username && proxy.password ? `${encodeURIComponent(proxy.username)}:${encodeURIComponent(proxy.password)}@` : "";
    let httpUrl;
    let allUrl;
    if (proxy.proxyType === "socks5") {
      httpUrl = `socks5://${auth}${proxy.host}:${proxy.port}`;
      allUrl = `socks5://${auth}${proxy.host}:${proxy.port}`;
    } else {
      httpUrl = `http://${auth}${proxy.host}:${proxy.port}`;
      allUrl = `http://${auth}${proxy.host}:${proxy.port}`;
    }
    const keys = [
      "HTTP_PROXY",
      "HTTPS_PROXY",
      "ALL_PROXY",
      "http_proxy",
      "https_proxy",
      "all_proxy"
    ];
    for (const key of keys) {
      if (!this.originalEnv.has(key)) {
        this.originalEnv.set(key, process.env[key]);
      }
    }
    process.env.HTTP_PROXY = httpUrl;
    process.env.HTTPS_PROXY = httpUrl;
    process.env.ALL_PROXY = allUrl;
    process.env.http_proxy = httpUrl;
    process.env.https_proxy = httpUrl;
    process.env.all_proxy = allUrl;
  }
  clearEnvironmentProxy() {
    const keys = [
      "HTTP_PROXY",
      "HTTPS_PROXY",
      "ALL_PROXY",
      "http_proxy",
      "https_proxy",
      "all_proxy"
    ];
    for (const key of keys) {
      const original = this.originalEnv.get(key);
      if (original === void 0) {
        delete process.env[key];
      } else {
        process.env[key] = original;
      }
    }
    this.originalEnv.clear();
  }
  // ──────────────────────────────────────────────────────────
  //  PROXY APPLY / CLEAR
  // ──────────────────────────────────────────────────────────
  /**
   * Apply proxy to ALL discovered sessions + env vars + login handler.
   *
   * Three-layer approach:
   *   1) session.setProxy({ mode: 'fixed_servers', proxyRules })
   *   2) session.on('login', handler) — for 407 proxy auth
   *   3) process.env — for Node.js stack
   */
  async applyProxy() {
    const proxy = this.getActiveProxy();
    if (!proxy) {
      new import_obsidian.Notice("Obsi Proxy: no proxy selected");
      return false;
    }
    const rules = this.buildProxyRules(proxy);
    if (!rules) {
      new import_obsidian.Notice("Obsi Proxy: host and port are required");
      return false;
    }
    const sessions = await this.getAllSessions();
    let applied = 0;
    for (const session of sessions) {
      try {
        await session.setProxy({
          mode: "fixed_servers",
          proxyRules: rules,
          proxyBypassRules: ""
        });
        applied++;
      } catch (err) {
        console.error("Obsi Proxy: setProxy failed on session", err);
      }
    }
    await this.registerLoginHandlers(proxy);
    this.setEnvironmentProxy(proxy);
    if (applied === 0) {
      new import_obsidian.Notice(
        "Obsi Proxy: could not apply proxy to any Electron session. Run Diagnostics for details."
      );
      return false;
    }
    let verified = false;
    for (const session of sessions) {
      try {
        const resolved = await session.resolveProxy(
          "https://example.com"
        );
        if (resolved && resolved !== "DIRECT") {
          verified = true;
          break;
        }
      } catch (e) {
      }
    }
    if (!verified && applied > 0) {
      console.warn(
        "Obsi Proxy: setProxy was called but resolveProxy returns DIRECT \u2014 proxy may not have taken effect"
      );
    }
    console.log(
      `Obsi Proxy: applied to ${applied}/${sessions.length} sessions, login handler registered, env vars set, verified=${verified}`
    );
    console.log(`Obsi Proxy: proxyRules = "${rules}"`);
    new import_obsidian.Notice(
      `Obsi Proxy: ON \u2014 ${proxy.name} (${applied} sessions${verified ? ", verified" : ""})`
    );
    return true;
  }
  /**
   * Clear proxy from ALL sessions + restore env + remove login handler.
   */
  async clearProxy() {
    await this.unregisterLoginHandlers();
    const sessions = await this.getAllSessions();
    for (const session of sessions) {
      try {
        await session.setProxy({
          mode: "system",
          proxyRules: "",
          proxyBypassRules: ""
        });
      } catch (err) {
        console.error("Obsi Proxy: clearProxy failed on session", err);
      }
    }
    this.clearEnvironmentProxy();
  }
  async enableProxy() {
    const ok = await this.applyProxy();
    this.settings.enabled = ok;
    await this.saveSettings();
    if (ok) {
      this.startSessionWatch();
    }
  }
  async disableProxy() {
    this.stopSessionWatch();
    await this.clearProxy();
    this.settings.enabled = false;
    await this.saveSettings();
    new import_obsidian.Notice("Obsi Proxy: OFF \u2014 direct connection restored");
  }
  // ──────────────────────────────────────────────────────────
  //  PERIODIC SESSION REFRESH
  // ──────────────────────────────────────────────────────────
  /**
   * Re-apply proxy + login handler every 30s to catch new sessions.
   */
  startSessionWatch() {
    if (this.sessionWatchInterval)
      return;
    this.sessionWatchInterval = window.setInterval(async () => {
      if (!this.settings.enabled || !this.getActiveProxy())
        return;
      const proxy = this.getActiveProxy();
      const rules = this.buildProxyRules(proxy);
      if (!rules)
        return;
      const sessions = await this.getAllSessions();
      for (const session of sessions) {
        try {
          await session.setProxy({
            mode: "fixed_servers",
            proxyRules: rules,
            proxyBypassRules: ""
          });
        } catch (e) {
        }
        if (this.loginHandler) {
          try {
            session.removeListener("login", this.loginHandler);
            session.on("login", this.loginHandler);
          } catch (e) {
          }
        }
      }
    }, 3e4);
  }
  stopSessionWatch() {
    if (this.sessionWatchInterval !== null) {
      window.clearInterval(this.sessionWatchInterval);
      this.sessionWatchInterval = null;
    }
  }
  // ──────────────────────────────────────────────────────────
  //  CONNECTION CHECK
  // ──────────────────────────────────────────────────────────
  /**
   * Check proxy by making a test request.
   * Works even when proxy is NOT currently active:
   *   1. Temporarily apply proxy to ALL sessions + env vars
   *   2. Wait 500ms for Chromium to update proxy config
   *   3. Make test request to ipify.org
   *   4. Revert to previous state
   */
  async checkConnection(proxy) {
    const isActive = this.settings.enabled && this.settings.activeProxyId === proxy.id;
    let needsRevert = false;
    if (!isActive) {
      const rules = this.buildProxyRules(proxy);
      if (!rules)
        return null;
      const sessions = await this.getAllSessions();
      for (const session of sessions) {
        try {
          await session.setProxy({
            mode: "fixed_servers",
            proxyRules: rules,
            proxyBypassRules: ""
          });
        } catch (e) {
        }
      }
      if (proxy.username && proxy.password) {
        const handler = this.createLoginHandler(proxy);
        for (const session of sessions) {
          try {
            session.on("login", handler);
          } catch (e) {
          }
        }
      }
      this.setEnvironmentProxy(proxy);
      needsRevert = true;
      await new Promise((resolve) => setTimeout(resolve, 500));
    }
    try {
      const resp = await (0, import_obsidian.requestUrl)({
        url: "https://api.ipify.org?format=json",
        method: "GET"
      });
      return resp.json;
    } catch (err) {
      console.error("Obsi Proxy check error:", err);
      return null;
    } finally {
      if (needsRevert) {
        if (this.settings.enabled && this.getActiveProxy()) {
          const activeProxy = this.getActiveProxy();
          const activeRules = this.buildProxyRules(activeProxy);
          const sessions = await this.getAllSessions();
          for (const session of sessions) {
            try {
              await session.setProxy({
                mode: "fixed_servers",
                proxyRules: activeRules,
                proxyBypassRules: ""
              });
            } catch (e) {
            }
          }
          await this.registerLoginHandlers(activeProxy);
          this.setEnvironmentProxy(activeProxy);
        } else {
          const sessions = await this.getAllSessions();
          for (const session of sessions) {
            try {
              await session.setProxy({
                mode: "system",
                proxyRules: "",
                proxyBypassRules: ""
              });
            } catch (e) {
            }
          }
          await this.unregisterLoginHandlers();
          this.clearEnvironmentProxy();
        }
      }
    }
  }
  // ──────────────────────────────────────────────────────────
  //  DIAGNOSTICS
  // ──────────────────────────────────────────────────────────
  async getDiagnostics() {
    const lines = [];
    lines.push("=== Obsi Proxy Diagnostics ===");
    lines.push("");
    const hasRequire = typeof window.require === "function";
    lines.push(`window.require available: ${hasRequire}`);
    if (hasRequire) {
      try {
        const electron = window.require("electron");
        lines.push(`electron.remote available: ${!!electron.remote}`);
        try {
          const remote = window.require("@electron/remote");
          lines.push(`@electron/remote available: ${!!remote}`);
        } catch (e) {
          lines.push("@electron/remote available: false");
        }
      } catch (e) {
        lines.push("electron require failed");
      }
    }
    const sessions = await this.getAllSessions();
    lines.push(`Sessions discovered: ${sessions.length}`);
    for (let i = 0; i < sessions.length; i++) {
      const session = sessions[i];
      try {
        const resolved = await session.resolveProxy(
          "https://example.com"
        );
        lines.push(`  Session ${i}: resolveProxy = "${resolved}"`);
      } catch (err) {
        lines.push(`  Session ${i}: resolveProxy failed \u2014 ${err}`);
      }
    }
    lines.push("");
    lines.push("Environment variables:");
    for (const key of [
      "HTTP_PROXY",
      "HTTPS_PROXY",
      "ALL_PROXY",
      "http_proxy",
      "https_proxy",
      "all_proxy"
    ]) {
      const val = process.env[key];
      if (val) {
        const masked = val.replace(/:[^@]+@/, ":****@");
        lines.push(`  ${key} = ${masked}`);
      } else {
        lines.push(`  ${key} = (not set)`);
      }
    }
    lines.push("");
    lines.push(`Proxy enabled: ${this.settings.enabled}`);
    lines.push(`Active proxy ID: ${this.settings.activeProxyId || "(none)"}`);
    lines.push(`Saved proxies: ${this.settings.proxies.length}`);
    lines.push(`Session watch active: ${this.sessionWatchInterval !== null}`);
    lines.push(`Login handler registered: ${this.loginHandler !== null}`);
    const active = this.getActiveProxy();
    if (active) {
      lines.push("");
      lines.push("Active proxy details:");
      lines.push(`  Name: ${active.name}`);
      lines.push(`  Type: ${active.proxyType}`);
      lines.push(`  Host: ${active.host}`);
      lines.push(`  Port: ${active.port}`);
      lines.push(`  Has auth: ${!!(active.username && active.password)}`);
      lines.push(`  proxyRules: "${this.buildProxyRules(active)}"`);
    }
    return lines.join("\n");
  }
};
var ProxyCheckModal = class extends import_obsidian.Modal {
  constructor(app, proxyName, result, error, wasActiveWhenChecked) {
    super(app);
    this.proxyName = proxyName;
    this.result = result;
    this.error = error;
    this.wasActiveWhenChecked = wasActiveWhenChecked;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Proxy Connection Check" });
    contentEl.createEl("p", {
      text: `Checking: ${this.proxyName}`,
      cls: "obsi-proxy-check-result"
    });
    if (!this.wasActiveWhenChecked) {
      contentEl.createEl("p", {
        text: "Note: This proxy was temporarily applied for the check and then reverted to your previous state.",
        attr: {
          style: "font-style: italic; color: var(--text-muted);"
        }
      });
    }
    if (this.error) {
      contentEl.createEl("p", {
        text: `Error: ${this.error}`,
        cls: "obsi-proxy-check-result",
        attr: {
          style: "background: var(--background-modifier-error); color: var(--text-error);"
        }
      });
      contentEl.createEl("p", {
        text: "The proxy server is unreachable or the credentials are incorrect. Try another proxy or hit Emergency Disable."
      });
    } else if (this.result) {
      contentEl.createEl("p", {
        text: `Outgoing IP: ${this.result.ip}`,
        cls: "obsi-proxy-check-result",
        attr: {
          style: "background: var(--background-modifier-success); color: var(--text-success); font-size: 16px; font-weight: 600;"
        }
      });
      contentEl.createEl("p", {
        text: this.wasActiveWhenChecked ? "This IP belongs to your proxy server. Connection is working correctly." : "This is the IP that would be seen if you enable this proxy. Connection is working correctly."
      });
    }
    new import_obsidian.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Close").onClick(() => this.close())
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ProxyEditModal = class extends import_obsidian.Modal {
  constructor(app, plugin, entry, isNew, onSave) {
    super(app);
    this.plugin = plugin;
    this.entry = { ...entry };
    this.isNew = isNew;
    this.onSave = onSave;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", {
      text: this.isNew ? "Add Proxy" : "Edit Proxy"
    });
    new import_obsidian.Setting(contentEl).setName("Name").setDesc("A friendly name for this proxy").addText(
      (text) => text.setPlaceholder("e.g. Work VPN").setValue(this.entry.name).onChange((val) => {
        this.entry.name = val;
      })
    );
    new import_obsidian.Setting(contentEl).setName("Proxy type").setDesc(
      "HTTP routes HTTP/HTTPS traffic through HTTP CONNECT. SOCKS5 proxies all TCP with DNS on the proxy side."
    ).addDropdown(
      (dd) => dd.addOption("http", "HTTP").addOption("socks5", "SOCKS5").setValue(this.entry.proxyType).onChange((val) => {
        this.entry.proxyType = val;
      })
    );
    new import_obsidian.Setting(contentEl).setName("Host").setDesc("IP address or hostname of the proxy server").addText(
      (text) => text.setPlaceholder("e.g. 167.148.96.23").setValue(this.entry.host).onChange((val) => {
        this.entry.host = val.trim();
      })
    );
    new import_obsidian.Setting(contentEl).setName("Port").setDesc("Port number of the proxy server").addText(
      (text) => text.setPlaceholder("e.g. 47866").setValue(this.entry.port).onChange((val) => {
        this.entry.port = val.trim();
      })
    );
    new import_obsidian.Setting(contentEl).setName("Username").setDesc("Leave empty if proxy does not require authentication").addText(
      (text) => text.setPlaceholder("optional").setValue(this.entry.username).onChange((val) => {
        this.entry.username = val;
      })
    );
    new import_obsidian.Setting(contentEl).setName("Password").setDesc("Leave empty if proxy does not require authentication").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("optional").setValue(this.entry.password).onChange((val) => {
        this.entry.password = val;
      });
    });
    new import_obsidian.Setting(contentEl).addButton(
      (btn) => btn.setButtonText(this.isNew ? "Add Proxy" : "Save Changes").setCta().onClick(() => {
        if (!this.entry.name.trim()) {
          this.entry.name = `${this.entry.proxyType}://${this.entry.host}:${this.entry.port}`;
        }
        if (!this.entry.host || !this.entry.port) {
          new import_obsidian.Notice("Obsi Proxy: host and port are required");
          return;
        }
        this.onSave(this.entry);
        this.close();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};
var DiagnosticsModal = class extends import_obsidian.Modal {
  constructor(app, diagText) {
    super(app);
    this.diagText = diagText;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Obsi Proxy Diagnostics" });
    const pre = contentEl.createEl("pre", {
      cls: "obsi-proxy-check-result",
      attr: {
        style: "background: var(--background-secondary); padding: 16px; border-radius: 6px; overflow-x: auto; max-height: 400px; white-space: pre-wrap;"
      }
    });
    pre.textContent = this.diagText;
    new import_obsidian.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Copy to Clipboard").onClick(() => {
        navigator.clipboard.writeText(this.diagText);
        new import_obsidian.Notice("Copied to clipboard");
      })
    );
    new import_obsidian.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Close").onClick(() => this.close())
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ObsiProxySettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.statusEl = null;
    this.proxyListEl = null;
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("obsi-proxy-settings");
    containerEl.createEl("h2", { text: "Obsi Proxy" });
    this.renderStatus(containerEl);
    this.renderToggle(containerEl);
    this.renderProxyList(containerEl);
    this.renderEmergency(containerEl);
    this.renderDiagnostics(containerEl);
  }
  renderStatus(parent) {
    const active = this.plugin.getActiveProxy();
    const text = this.plugin.settings.enabled && active ? `ON \u2014 ${active.name} (${active.proxyType}://${active.host}:${active.port})` : "OFF \u2014 direct connection";
    this.statusEl = parent.createEl("div", {
      cls: `obsi-proxy-status ${this.plugin.settings.enabled ? "active" : "inactive"}`,
      text: `Obsi Proxy: ${text}`
    });
  }
  renderToggle(parent) {
    new import_obsidian.Setting(parent).setName("Enable proxy").setDesc(
      "Route all Obsidian and plugin traffic through the selected proxy"
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enabled).onChange(async (val) => {
        if (val) {
          if (!this.plugin.getActiveProxy()) {
            new import_obsidian.Notice("Obsi Proxy: select a proxy first");
            toggle.setValue(false);
            return;
          }
          await this.plugin.enableProxy();
        } else {
          await this.plugin.disableProxy();
        }
        this.display();
      })
    );
  }
  renderProxyList(parent) {
    parent.createEl("div", {
      text: "PROXY LIST",
      cls: "obsi-proxy-section-title"
    });
    this.proxyListEl = parent.createEl("div");
    this.plugin.settings.proxies.forEach((proxy) => {
      this.renderProxyItem(proxy);
    });
    if (this.plugin.settings.proxies.length === 0) {
      this.proxyListEl.createEl("p", {
        text: "No proxies configured. Add one below.",
        attr: { style: "color: var(--text-muted); padding: 8px 0;" }
      });
    }
    new import_obsidian.Setting(parent).setName("Add new proxy").setDesc("Add an HTTP or SOCKS5 proxy server").addButton(
      (btn) => btn.setButtonText("+ Add Proxy").setCta().onClick(() => {
        const newEntry = {
          id: generateId(),
          name: "",
          proxyType: "http",
          host: "",
          port: "",
          username: "",
          password: ""
        };
        const modal = new ProxyEditModal(
          this.app,
          this.plugin,
          newEntry,
          true,
          async (entry) => {
            this.plugin.settings.proxies.push(entry);
            if (!this.plugin.settings.activeProxyId || this.plugin.settings.proxies.length === 1) {
              this.plugin.settings.activeProxyId = entry.id;
            }
            await this.plugin.saveSettings();
            this.display();
          }
        );
        modal.open();
      })
    );
  }
  renderProxyItem(proxy) {
    if (!this.proxyListEl)
      return;
    const isSelected = this.plugin.settings.activeProxyId === proxy.id;
    const item = this.proxyListEl.createEl("div", {
      cls: `obsi-proxy-list-item ${isSelected ? "selected" : ""}`
    });
    item.addEventListener("click", async (e) => {
      const target = e.target;
      if (target.closest("button"))
        return;
      this.plugin.settings.activeProxyId = proxy.id;
      await this.plugin.saveSettings();
      if (this.plugin.settings.enabled) {
        await this.plugin.enableProxy();
      }
      this.display();
    });
    const header = item.createEl("div", {
      cls: "obsi-proxy-list-item-header"
    });
    header.createEl("span", {
      text: isSelected ? `\u25B6 ${proxy.name}` : proxy.name,
      cls: "obsi-proxy-list-item-name"
    });
    const actions = header.createEl("div", {
      cls: "obsi-proxy-list-item-actions"
    });
    const checkBtn = actions.createEl("button", {
      text: "Check"
    });
    checkBtn.addEventListener("click", async (e) => {
      e.stopPropagation();
      checkBtn.textContent = "...";
      checkBtn.setAttribute("disabled", "true");
      const wasActive = this.plugin.settings.enabled && this.plugin.settings.activeProxyId === proxy.id;
      const result = await this.plugin.checkConnection(proxy);
      const error = result === null ? "Connection failed \u2014 proxy may be unreachable or credentials are wrong" : null;
      checkBtn.textContent = "Check";
      checkBtn.removeAttribute("disabled");
      if (error) {
        new import_obsidian.Notice("Obsi Proxy: check failed", 5e3);
      } else if (result) {
        new import_obsidian.Notice(`Obsi Proxy: IP is ${result.ip}`, 5e3);
      }
      const modal = new ProxyCheckModal(
        this.app,
        proxy.name,
        result,
        error,
        wasActive
      );
      modal.open();
    });
    const editBtn = actions.createEl("button", {
      text: "Edit"
    });
    editBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      const modal = new ProxyEditModal(
        this.app,
        this.plugin,
        proxy,
        false,
        async (entry) => {
          const idx = this.plugin.settings.proxies.findIndex(
            (p) => p.id === entry.id
          );
          if (idx >= 0) {
            this.plugin.settings.proxies[idx] = entry;
          }
          await this.plugin.saveSettings();
          if (this.plugin.settings.enabled && this.plugin.settings.activeProxyId === entry.id) {
            await this.plugin.enableProxy();
          }
          this.display();
        }
      );
      modal.open();
    });
    const delBtn = actions.createEl("button", {
      text: "Delete"
    });
    delBtn.addEventListener("click", async (e) => {
      e.stopPropagation();
      this.plugin.settings.proxies = this.plugin.settings.proxies.filter((p) => p.id !== proxy.id);
      if (this.plugin.settings.activeProxyId === proxy.id) {
        this.plugin.settings.activeProxyId = this.plugin.settings.proxies.length > 0 ? this.plugin.settings.proxies[0].id : "";
        if (this.plugin.settings.enabled) {
          if (this.plugin.getActiveProxy()) {
            await this.plugin.enableProxy();
          } else {
            await this.plugin.disableProxy();
          }
        }
      }
      await this.plugin.saveSettings();
      this.display();
    });
    item.createEl("div", {
      text: `${proxy.proxyType}://${proxy.host}:${proxy.port}${proxy.username ? " (auth)" : ""}${isSelected ? " \u2014 selected" : ""}`,
      cls: "obsi-proxy-list-item-detail"
    });
  }
  renderEmergency(parent) {
    new import_obsidian.Setting(parent).setName("Emergency Disable").setDesc(
      "Instantly clear all proxy rules and restore direct connection"
    ).addButton(
      (btn) => btn.setButtonText("Disable Proxy Now").setWarning().onClick(async () => {
        await this.plugin.disableProxy();
        this.display();
      })
    );
  }
  renderDiagnostics(parent) {
    parent.createEl("div", {
      text: "DIAGNOSTICS",
      cls: "obsi-proxy-section-title"
    });
    new import_obsidian.Setting(parent).setName("Run diagnostics").setDesc(
      "Check Electron session access, proxy state, and environment variables"
    ).addButton(
      (btn) => btn.setButtonText("Run Diagnostics").onClick(async () => {
        btn.setButtonText("Running...");
        btn.setDisabled(true);
        const diag = await this.plugin.getDiagnostics();
        btn.setButtonText("Run Diagnostics");
        btn.setDisabled(false);
        const modal = new DiagnosticsModal(this.app, diag);
        modal.open();
      })
    );
  }
  refreshStatus() {
    if (!this.statusEl)
      return;
    const active = this.plugin.getActiveProxy();
    const text = this.plugin.settings.enabled && active ? `ON \u2014 ${active.name} (${active.proxyType}://${active.host}:${active.port})` : "OFF \u2014 direct connection";
    this.statusEl.className = `obsi-proxy-status ${this.plugin.settings.enabled ? "active" : "inactive"}`;
    this.statusEl.textContent = `Obsi Proxy: ${text}`;
  }
};
