/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ObsiProxyPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  enabled: false,
  activeProxyId: "",
  proxies: []
};
function generateId() {
  return Date.now().toString(36) + Math.random().toString(36).slice(2, 8);
}
var ObsiProxyPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new ObsiProxySettingTab(this.app, this));
    if (this.settings.enabled && this.getActiveProxy()) {
      await this.applyProxy();
    }
  }
  async onunload() {
    await this.clearProxy();
  }
  async loadSettings() {
    const loaded = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, loaded);
    if (!this.settings.proxies) {
      this.settings.proxies = [];
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  getActiveProxy() {
    var _a;
    if (!this.settings.activeProxyId)
      return null;
    return (_a = this.settings.proxies.find(
      (p) => p.id === this.settings.activeProxyId
    )) != null ? _a : null;
  }
  /**
   * Build a Chromium-compatible proxyRules string from a ProxyEntry.
   *
   * Chromium docs:
   *   https://www.chromium.org/developers/design-documents/network-settings/
   */
  buildProxyRules(proxy) {
    const { proxyType, host, port, username, password } = proxy;
    if (!host || !port)
      return "";
    const auth = username && password ? `${encodeURIComponent(username)}:${encodeURIComponent(password)}@` : "";
    if (proxyType === "socks5") {
      return `socks5://${auth}${host}:${port}`;
    }
    return `http=${auth}${host}:${port};https=${auth}${host}:${port}`;
  }
  /**
   * Get the Electron session object.
   *
   * Obsidian gives us access to Electron via:
   *   (window as any).require('electron')
   *
   * We need defaultSession from either remote.session
   * or directly from electron.session (depends on
   * Electron version and contextIsolation settings).
   */
  getSession() {
    var _a, _b, _c, _d, _e;
    try {
      const electron = window.require("electron");
      return (_e = (_d = (_b = (_a = electron.remote) == null ? void 0 : _a.session) == null ? void 0 : _b.defaultSession) != null ? _d : (_c = electron.session) == null ? void 0 : _c.defaultSession) != null ? _e : null;
    } catch (e) {
      return null;
    }
  }
  /**
   * Apply proxy rules to the Electron session.
   *
   * This is the core call that makes ALL Obsidian + plugin traffic
   * go through the proxy. After this call, every new HTTP/HTTPS/TCP
   * connection from the renderer process will be routed through the
   * specified proxy server.
   */
  async applyProxy() {
    var _a;
    const proxy = this.getActiveProxy();
    if (!proxy) {
      new import_obsidian.Notice("Obsi Proxy: no proxy selected");
      return false;
    }
    const rules = this.buildProxyRules(proxy);
    if (!rules) {
      new import_obsidian.Notice("Obsi Proxy: host and port are required");
      return false;
    }
    const session = this.getSession();
    if (!session) {
      new import_obsidian.Notice("Obsi Proxy: cannot access Electron session");
      return false;
    }
    try {
      await session.setProxy({
        proxyRules: rules,
        proxyBypassRules: ""
      });
      new import_obsidian.Notice(
        `Obsi Proxy: ON \u2014 ${proxy.name} (${proxy.proxyType}://${proxy.host}:${proxy.port})`
      );
      return true;
    } catch (err) {
      console.error("Obsi Proxy apply error:", err);
      new import_obsidian.Notice(
        `Obsi Proxy: error \u2014 ${(_a = err.message) != null ? _a : err}`
      );
      return false;
    }
  }
  /**
   * Clear proxy rules — all traffic returns to direct connection.
   */
  async clearProxy() {
    const session = this.getSession();
    if (!session)
      return;
    try {
      await session.setProxy({
        proxyRules: "",
        proxyBypassRules: ""
      });
    } catch (err) {
      console.error("Obsi Proxy clear error:", err);
    }
  }
  async enableProxy() {
    const ok = await this.applyProxy();
    this.settings.enabled = ok;
    await this.saveSettings();
  }
  async disableProxy() {
    await this.clearProxy();
    this.settings.enabled = false;
    await this.saveSettings();
    new import_obsidian.Notice("Obsi Proxy: OFF \u2014 direct connection restored");
  }
  /**
   * Apply a specific proxy (by entry) to the session.
   * Used for temporarily checking a proxy that isn't currently active.
   */
  async applySpecificProxy(proxy) {
    const rules = this.buildProxyRules(proxy);
    if (!rules)
      return false;
    const session = this.getSession();
    if (!session)
      return false;
    try {
      await session.setProxy({
        proxyRules: rules,
        proxyBypassRules: ""
      });
      return true;
    } catch (e) {
      return false;
    }
  }
  /**
   * Connection check.
   *
   * If proxy is enabled and this is the active proxy — just check directly.
   * If proxy is NOT enabled — temporarily apply the proxy, check, then
   * revert to the previous state (either direct or previous active proxy).
   *
   * This ensures the checker works regardless of whether the proxy
   * is currently connected or not.
   */
  async checkConnection(proxy) {
    const isActive = this.settings.enabled && this.settings.activeProxyId === proxy.id;
    let needsRevert = false;
    if (!isActive) {
      const applied = await this.applySpecificProxy(proxy);
      if (!applied)
        return null;
      needsRevert = true;
    }
    try {
      const resp = await (0, import_obsidian.requestUrl)({
        url: "https://api.ipify.org?format=json",
        method: "GET"
      });
      return resp.json;
    } catch (err) {
      console.error("Obsi Proxy check error:", err);
      return null;
    } finally {
      if (needsRevert) {
        if (this.settings.enabled && this.getActiveProxy()) {
          await this.applyProxy();
        } else {
          await this.clearProxy();
        }
      }
    }
  }
};
var ProxyCheckModal = class extends import_obsidian.Modal {
  constructor(app, proxyName, result, error, wasActiveWhenChecked) {
    super(app);
    this.proxyName = proxyName;
    this.result = result;
    this.error = error;
    this.wasActiveWhenChecked = wasActiveWhenChecked;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("obsi-proxy-check-modal");
    contentEl.createEl("h2", { text: "Proxy Connection Check" });
    contentEl.createEl("p", {
      text: `Checking: ${this.proxyName}`,
      cls: "obsi-proxy-check-result"
    });
    if (!this.wasActiveWhenChecked) {
      contentEl.createEl("p", {
        text: "Note: Proxy was not active. It was temporarily applied for this check and then reverted.",
        attr: { style: "font-style: italic; color: var(--text-muted);" }
      });
    }
    if (this.error) {
      contentEl.createEl("p", {
        text: `Error: ${this.error}`,
        cls: "obsi-proxy-check-result",
        attr: {
          style: "background: var(--background-modifier-error); color: var(--text-error);"
        }
      });
      contentEl.createEl("p", {
        text: "The proxy server is unreachable or the credentials are incorrect. You can try another proxy or hit Emergency Disable."
      });
    } else if (this.result) {
      contentEl.createEl("p", {
        text: `Outgoing IP: ${this.result.ip}`,
        cls: "obsi-proxy-check-result",
        attr: {
          style: "background: var(--background-modifier-success); color: var(--text-success); font-size: 16px; font-weight: 600;"
        }
      });
      if (this.wasActiveWhenChecked) {
        contentEl.createEl("p", {
          text: "This IP belongs to your proxy server. Connection is working correctly."
        });
      } else {
        contentEl.createEl("p", {
          text: "This is the IP that would be seen if you enable this proxy. Connection is working correctly."
        });
      }
    }
    new import_obsidian.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Close").onClick(() => this.close())
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ProxyEditModal = class extends import_obsidian.Modal {
  constructor(app, plugin, entry, isNew, onSave) {
    super(app);
    this.plugin = plugin;
    this.entry = { ...entry };
    this.isNew = isNew;
    this.onSave = onSave;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", {
      text: this.isNew ? "Add Proxy" : "Edit Proxy"
    });
    new import_obsidian.Setting(contentEl).setName("Name").setDesc("A friendly name for this proxy").addText((text) => {
      text.setPlaceholder("e.g. Work VPN").setValue(this.entry.name).onChange((val) => {
        this.entry.name = val;
      });
      this.nameInput = text.inputEl;
    });
    new import_obsidian.Setting(contentEl).setName("Proxy type").setDesc("HTTP routes HTTP/HTTPS. SOCKS5 proxies all TCP with DNS on the proxy side.").addDropdown((dd) => {
      dd.addOption("http", "HTTP").addOption("socks5", "SOCKS5").setValue(this.entry.proxyType).onChange((val) => {
        this.entry.proxyType = val;
      });
      this.typeSelect = dd.selectEl;
    });
    new import_obsidian.Setting(contentEl).setName("Host").setDesc("IP address or hostname").addText((text) => {
      text.setPlaceholder("e.g. 127.0.0.1").setValue(this.entry.host).onChange((val) => {
        this.entry.host = val.trim();
      });
      this.hostInput = text.inputEl;
    });
    new import_obsidian.Setting(contentEl).setName("Port").setDesc("Port number").addText((text) => {
      text.setPlaceholder("e.g. 8080").setValue(this.entry.port).onChange((val) => {
        this.entry.port = val.trim();
      });
      this.portInput = text.inputEl;
    });
    new import_obsidian.Setting(contentEl).setName("Username").setDesc("Leave empty if not required").addText((text) => {
      text.setPlaceholder("optional").setValue(this.entry.username).onChange((val) => {
        this.entry.username = val;
      });
      this.usernameInput = text.inputEl;
    });
    new import_obsidian.Setting(contentEl).setName("Password").setDesc("Leave empty if not required").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("optional").setValue(this.entry.password).onChange((val) => {
        this.entry.password = val;
      });
      this.passwordInput = text.inputEl;
    });
    new import_obsidian.Setting(contentEl).addButton(
      (btn) => btn.setButtonText(this.isNew ? "Add Proxy" : "Save Changes").setCta().onClick(() => {
        if (!this.entry.name.trim()) {
          this.entry.name = `${this.entry.proxyType}://${this.entry.host}:${this.entry.port}`;
        }
        if (!this.entry.host || !this.entry.port) {
          new import_obsidian.Notice("Obsi Proxy: host and port are required");
          return;
        }
        this.onSave(this.entry);
        this.close();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ObsiProxySettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.statusEl = null;
    this.proxyListEl = null;
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("obsi-proxy-settings");
    containerEl.createEl("h2", { text: "Obsi Proxy" });
    this.renderStatus(containerEl);
    this.renderToggle(containerEl);
    this.renderProxyList(containerEl);
    this.renderEmergency(containerEl);
  }
  renderStatus(parent) {
    const active = this.plugin.getActiveProxy();
    const text = this.plugin.settings.enabled && active ? `ON \u2014 ${active.name} (${active.proxyType}://${active.host}:${active.port})` : "OFF \u2014 direct connection";
    this.statusEl = parent.createEl("div", {
      cls: `obsi-proxy-status ${this.plugin.settings.enabled ? "active" : "inactive"}`,
      text: `Obsi Proxy: ${text}`
    });
  }
  renderToggle(parent) {
    new import_obsidian.Setting(parent).setName("Enable proxy").setDesc("Route all Obsidian and plugin traffic through the selected proxy").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enabled).onChange(async (val) => {
        if (val) {
          if (!this.plugin.getActiveProxy()) {
            new import_obsidian.Notice("Obsi Proxy: select a proxy first");
            toggle.setValue(false);
            return;
          }
          await this.plugin.enableProxy();
        } else {
          await this.plugin.disableProxy();
        }
        this.refreshStatus();
      })
    );
  }
  renderProxyList(parent) {
    parent.createEl("div", {
      text: "PROXY LIST",
      cls: "obsi-proxy-section-title"
    });
    this.proxyListEl = parent.createEl("div");
    this.plugin.settings.proxies.forEach((proxy) => {
      this.renderProxyItem(proxy);
    });
    if (this.plugin.settings.proxies.length === 0) {
      this.proxyListEl.createEl("p", {
        text: "No proxies configured. Add one below.",
        attr: { style: "color: var(--text-muted); padding: 8px 0;" }
      });
    }
    new import_obsidian.Setting(parent).setName("Add new proxy").setDesc("Add an HTTP or SOCKS5 proxy server").addButton(
      (btn) => btn.setButtonText("+ Add Proxy").setCta().onClick(() => {
        const newEntry = {
          id: generateId(),
          name: "",
          proxyType: "http",
          host: "",
          port: "",
          username: "",
          password: ""
        };
        const modal = new ProxyEditModal(
          this.app,
          this.plugin,
          newEntry,
          true,
          async (entry) => {
            this.plugin.settings.proxies.push(entry);
            if (!this.plugin.settings.activeProxyId || this.plugin.settings.proxies.length === 1) {
              this.plugin.settings.activeProxyId = entry.id;
            }
            await this.plugin.saveSettings();
            this.display();
          }
        );
        modal.open();
      })
    );
  }
  renderProxyItem(proxy) {
    if (!this.proxyListEl)
      return;
    const isSelected = this.plugin.settings.activeProxyId === proxy.id;
    const item = this.proxyListEl.createEl("div", {
      cls: `obsi-proxy-list-item ${isSelected ? "selected" : ""}`
    });
    item.addEventListener("click", async (e) => {
      const target = e.target;
      if (target.closest("button"))
        return;
      this.plugin.settings.activeProxyId = proxy.id;
      await this.plugin.saveSettings();
      if (this.plugin.settings.enabled) {
        await this.plugin.enableProxy();
      }
      this.display();
    });
    const header = item.createEl("div", {
      cls: "obsi-proxy-list-item-header"
    });
    header.createEl("span", {
      text: isSelected ? `> ${proxy.name}` : proxy.name,
      cls: "obsi-proxy-list-item-name"
    });
    const actions = header.createEl("div", {
      cls: "obsi-proxy-list-item-actions"
    });
    const checkBtn = actions.createEl("button", {
      text: "Check"
    });
    checkBtn.addEventListener("click", async (e) => {
      e.stopPropagation();
      checkBtn.textContent = "...";
      checkBtn.setAttribute("disabled", "true");
      const wasActive = this.plugin.settings.enabled && this.plugin.settings.activeProxyId === proxy.id;
      const result = await this.plugin.checkConnection(proxy);
      const error = result === null ? "Connection failed \u2014 proxy may be unreachable or credentials are wrong" : null;
      checkBtn.textContent = "Check";
      checkBtn.removeAttribute("disabled");
      if (error) {
        new import_obsidian.Notice("Obsi Proxy: check failed", 5e3);
      } else if (result) {
        new import_obsidian.Notice(`Obsi Proxy: IP is ${result.ip}`, 5e3);
      }
      const modal = new ProxyCheckModal(
        this.app,
        proxy.name,
        result,
        error,
        wasActive
      );
      modal.open();
    });
    const editBtn = actions.createEl("button", {
      text: "Edit"
    });
    editBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      const modal = new ProxyEditModal(
        this.app,
        this.plugin,
        proxy,
        false,
        async (entry) => {
          const idx = this.plugin.settings.proxies.findIndex(
            (p) => p.id === entry.id
          );
          if (idx >= 0) {
            this.plugin.settings.proxies[idx] = entry;
          }
          await this.plugin.saveSettings();
          if (this.plugin.settings.enabled && this.plugin.settings.activeProxyId === entry.id) {
            await this.plugin.enableProxy();
          }
          this.display();
        }
      );
      modal.open();
    });
    const delBtn = actions.createEl("button", {
      text: "Delete"
    });
    delBtn.addEventListener("click", async (e) => {
      e.stopPropagation();
      this.plugin.settings.proxies = this.plugin.settings.proxies.filter(
        (p) => p.id !== proxy.id
      );
      if (this.plugin.settings.activeProxyId === proxy.id) {
        this.plugin.settings.activeProxyId = this.plugin.settings.proxies.length > 0 ? this.plugin.settings.proxies[0].id : "";
        if (this.plugin.settings.enabled) {
          if (this.plugin.getActiveProxy()) {
            await this.plugin.enableProxy();
          } else {
            await this.plugin.disableProxy();
          }
        }
      }
      await this.plugin.saveSettings();
      this.display();
    });
    item.createEl("div", {
      text: `${proxy.proxyType}://${proxy.host}:${proxy.port}${proxy.username ? " (auth)" : ""}${isSelected ? " \u2014 selected" : ""}`,
      cls: "obsi-proxy-list-item-detail"
    });
  }
  renderEmergency(parent) {
    new import_obsidian.Setting(parent).setName("Emergency Disable").setDesc(
      "Instantly clear all proxy rules and restore direct connection"
    ).addButton(
      (btn) => btn.setButtonText("Disable Proxy Now").setWarning().onClick(async () => {
        await this.plugin.disableProxy();
        this.display();
      })
    );
  }
  refreshStatus() {
    if (!this.statusEl)
      return;
    const active = this.plugin.getActiveProxy();
    const text = this.plugin.settings.enabled && active ? `ON \u2014 ${active.name} (${active.proxyType}://${active.host}:${active.port})` : "OFF \u2014 direct connection";
    this.statusEl.className = `obsi-proxy-status ${this.plugin.settings.enabled ? "active" : "inactive"}`;
    this.statusEl.textContent = `Obsi Proxy: ${text}`;
  }
};
